/** Dependency-injection tokens for the Learner Wellbeing, Safety & Success Platform (P2-D05). */

// Repositories (Prisma/RLS adapters over the learner-wellbeing ports).
export const LW_WELLBEING_PROFILE_REPOSITORY = Symbol("LW_WELLBEING_PROFILE_REPOSITORY");
export const LW_HEALTH_RECORD_REPOSITORY = Symbol("LW_HEALTH_RECORD_REPOSITORY");
export const LW_BEHAVIOUR_RECORD_REPOSITORY = Symbol("LW_BEHAVIOUR_RECORD_REPOSITORY");
export const LW_COUNSELLING_CASE_REPOSITORY = Symbol("LW_COUNSELLING_CASE_REPOSITORY");
export const LW_SAFEGUARDING_CASE_REPOSITORY = Symbol("LW_SAFEGUARDING_CASE_REPOSITORY");
export const LW_SUPPORT_PLAN_REPOSITORY = Symbol("LW_SUPPORT_PLAN_REPOSITORY");
export const LW_INTERVENTION_PLAN_REPOSITORY = Symbol("LW_INTERVENTION_PLAN_REPOSITORY");

// Cross-domain read ports (directories over Student (P2-D03) / Person (P2-D01-M02)).
export const LW_STUDENT_DIRECTORY = Symbol("LW_STUDENT_DIRECTORY");
export const LW_PERSON_DIRECTORY = Symbol("LW_PERSON_DIRECTORY");

// Application services.
export const LW_WELLBEING_PROFILE_SERVICE = Symbol("LW_WELLBEING_PROFILE_SERVICE");
export const LW_HEALTH_RECORD_SERVICE = Symbol("LW_HEALTH_RECORD_SERVICE");
export const LW_BEHAVIOUR_RECORD_SERVICE = Symbol("LW_BEHAVIOUR_RECORD_SERVICE");
export const LW_COUNSELLING_CASE_SERVICE = Symbol("LW_COUNSELLING_CASE_SERVICE");
export const LW_SAFEGUARDING_CASE_SERVICE = Symbol("LW_SAFEGUARDING_CASE_SERVICE");
export const LW_SUPPORT_PLAN_SERVICE = Symbol("LW_SUPPORT_PLAN_SERVICE");
export const LW_INTERVENTION_PLAN_SERVICE = Symbol("LW_INTERVENTION_PLAN_SERVICE");
