/** Dependency-injection tokens for the Institutional Governance Platform (P2-D02). */

// Repositories (Prisma/RLS adapters over the governance ports).
export const GOVERNANCE_BODY_REPOSITORY = Symbol("GOVERNANCE_BODY_REPOSITORY");
export const GOVERNANCE_COMMITTEE_REPOSITORY = Symbol("GOVERNANCE_COMMITTEE_REPOSITORY");
export const GOVERNANCE_POLICY_REPOSITORY = Symbol("GOVERNANCE_POLICY_REPOSITORY");
export const GOVERNANCE_POLICY_ACK_REPOSITORY = Symbol("GOVERNANCE_POLICY_ACK_REPOSITORY");
export const GOVERNANCE_DELEGATION_REPOSITORY = Symbol("GOVERNANCE_DELEGATION_REPOSITORY");
export const GOVERNANCE_RESOLUTION_REPOSITORY = Symbol("GOVERNANCE_RESOLUTION_REPOSITORY");
export const GOVERNANCE_CALENDAR_REPOSITORY = Symbol("GOVERNANCE_CALENDAR_REPOSITORY");

// Cross-domain read ports (directories over Organization / Person).
export const GOVERNANCE_ORGANIZATION_DIRECTORY = Symbol("GOVERNANCE_ORGANIZATION_DIRECTORY");
export const GOVERNANCE_PERSON_DIRECTORY = Symbol("GOVERNANCE_PERSON_DIRECTORY");

// Application services.
export const GOVERNANCE_BODY_SERVICE = Symbol("GOVERNANCE_BODY_SERVICE");
export const GOVERNANCE_COMMITTEE_SERVICE = Symbol("GOVERNANCE_COMMITTEE_SERVICE");
export const GOVERNANCE_POLICY_SERVICE = Symbol("GOVERNANCE_POLICY_SERVICE");
export const GOVERNANCE_DELEGATION_SERVICE = Symbol("GOVERNANCE_DELEGATION_SERVICE");
export const GOVERNANCE_RESOLUTION_SERVICE = Symbol("GOVERNANCE_RESOLUTION_SERVICE");
export const GOVERNANCE_CALENDAR_SERVICE = Symbol("GOVERNANCE_CALENDAR_SERVICE");
